const Class = require('./class')

function cClass(value, name){
    return new Class(value, name)
}

const classesData = [
    cClass("<!doctype", "DOCTYPE Tag"),
    cClass("<html", "HTML Tag"),
    cClass("<head", "Head Tag"),
    cClass("<title", "Title Tag"),
    cClass("<body", "Body Tag"),
    cClass("<h1", "H1 Tag"),
    cClass("<h2", "H2 Tag"),
    cClass("<h3", "H3 Tag"),
    cClass("<h4", "H4 Tag"),
    cClass("<h5", "H5 Tag"),
    cClass("<h6", "H6 Tag"),
    cClass("<p", "Paragraph Tag"),
    cClass("<a", "A Tag"),
    cClass("<img", "Image Tag"),
    cClass("<meta", "Meta Tag"),
    cClass("<style", "Style Tag"),
    cClass("<script", "Script Tag"),
    cClass("<link", "Link Tag"),
    cClass("<ul", "UL Tag"),
    cClass("<ol", "OL Tag"),
    cClass("<li", "LI Tag"),
    cClass("<div", "Div Tag"),
    cClass("<span", "Span Tag"),
    cClass("<table", "Table Tag"),
    cClass("<th", "TH Tag"),
    cClass("<tr", "TR Tag"),
    cClass("<td", "TD Tag"),
    cClass("<form", "Form Tag"),
    cClass("<button", "Button Tag"),
    cClass("<input", "Input Tag"),
    cClass("<label", "Label Tag"),
    cClass("<select", "Select Tag"),
    cClass("<section", "Section Tag"),
    cClass("<blockquote", "BlockQuote Tag"),
    cClass("<q", "Quote Tag"),
    cClass("<abbr", "Abbreviation Tag"),
    cClass("<cite", "Cite Tag"),
    cClass("<bdo", "Bi-Directional Override Tag"),
    cClass("<canva", "Canva Override Tag"),
    cClass("<address", "Address Tag"),
    cClass("<textarea", "Text Area Tag"),
    cClass("<option", "Option Tag"),
    cClass("<br", "Break Line Tag"),
    cClass("</br", "Break Line Tag"),

    cClass("</html", "Close HTML Tag"),
    cClass("</head", "Close Head Tag"),
    cClass("</title", "Close Title Tag"),
    cClass("</body", "Close Body Tag"),
    cClass("</h1", "Close H1 Tag"),
    cClass("</h2", "Close H2 Tag"),
    cClass("</h3", "Close H3 Tag"),
    cClass("</h4", "Close H4 Tag"),
    cClass("</h5", "Close H5 Tag"),
    cClass("</h6", "Close H6 Tag"),
    cClass("</style", "Close Style Tag"),
    cClass("</script", "Close Script Tag"),
    cClass("</p", "Close Paragraph Tag"),
    cClass("</a", "Close A Tag"),
    cClass("</img", "Close Image Tag"),
    cClass("</ul", "Close UL Tag"),
    cClass("</ol", "Close OL Tag"),
    cClass("</li", "Close LI Tag"),
    cClass("</div", "Close Div Tag"),
    cClass("</span", "Close Span Tag"),
    cClass("</table", "Close Table Tag"),
    cClass("</th", "Close TH Tag"),
    cClass("</tr", "Close TR Tag"),
    cClass("</td", "Close TD Tag"),
    cClass("</form", "Close Form Tag"),
    cClass("</button", "Close Button Tag"),
    cClass("</input", "Close Input Tag"),
    cClass("</label", "Close Label Tag"),
    cClass("</select", "Close Select Tag"),
    cClass("</section", "Close Section Tag"),
    cClass("</blockquote", "Close BlockQuote Tag"),
    cClass("</q", "Close Quote Tag"),
    cClass("</abbr", "Close Abbreviation Tag"),
    cClass("</cite", "Close Cite Tag"),
    cClass("</bdo", "Close Bi-Directional Override Tag"),
    cClass("</canva", "Close Canva Override Tag"),
    cClass("</address", "Close Address Tag"),
    cClass("</textarea", "Close Text Area Tag"),
    cClass("</option", "Close Option Tag"),
]

module.exports = classesData